# Generated by Django 6.0.1 on 2026-01-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="lasting",
            field=models.PositiveIntegerField(
                help_text="Укажите предположительное время на выполнение привычки в секундах",
                verbose_name="Время на выполнение",
            ),
        ),
    ]
